# Generated by Django 5.1.1 on 2024-10-10 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created_data',
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('shopping_cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shoppingcart')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
