# Generated by Django 5.1.1 on 2024-10-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_payment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
